export const API_ROUTES = {
  auditStart: "/api/tools/audit/start",
  auditStatus: (id: string) => `/api/tools/audit/status/${id}`,
  auditResult: (id: string) => `/api/tools/audit/result/${id}`,
  auditHistory: "/api/tools/audits/history",
  auditCompare: (currentId: string, baselineId: string) => `/api/tools/audit/compare/${encodeURIComponent(currentId)}/${encodeURIComponent(baselineId)}`,
  auditEvents: (id: string) => `/api/tools/audit/events/${id}`,
  auditCancel: (id: string) => `/api/tools/audit/cancel/${id}`,
  auditExport: (id: string, format: string) => `/api/tools/audit/export/${id}/${format}`,
  auditRerun: (id: string) => `/api/tools/audit/rerun/${id}`,
  auditArchive: (id: string) => `/api/tools/audit/archive/${id}`,
  auditDelete: (id: string) => `/api/tools/audit/${id}`,
  version: '/api/version',
  accountExport: '/api/tools/me/export',
  accountDelete: '/api/tools/me/delete',
  adminDiagnostics: '/api/tools/admin/diagnostics',
  meProfile: "/api/tools/me/profile",
  securityStart: "/api/tools/audit/start", // Based on the code, security audit calls /api/tools/audit/start with type="security"
  keywordResearch: "/api/tools/keyword/research",
  websiteAnalyze: "/api/tools/website/analyze",
  clusters: "/api/tools/clusters",
  contentBrief: "/api/tools/content-brief",
  competitorGap: "/api/tools/competitor-gap",
  blogPosts: "/api/tools/blog/posts",
  blogPost: (slug: string) => `/api/tools/blog/posts/${encodeURIComponent(slug)}`,
  adminBlogPosts: "/api/tools/admin/blog/posts",
  adminBlogPost: (id: string) => `/api/tools/admin/blog/posts/${encodeURIComponent(id)}`,
  adminBlogPostWorkflow: (id: string) => `/api/tools/admin/blog/posts/${encodeURIComponent(id)}/workflow`,
  adminBlogOverview: "/api/tools/admin/blog/overview",
  adminBlogSettings: "/api/tools/admin/blog/settings",
  adminBlogJobs: "/api/tools/admin/blog/jobs",
  adminBlogJobRetry: (id: string) => `/api/tools/admin/blog/jobs/${encodeURIComponent(id)}/retry`,
  adminBlogBatches: "/api/tools/admin/blog/batches",
  adminBlogImageImport: "/api/tools/admin/blog/images/import",
  adminBlogProviderTest: "/api/tools/admin/blog/provider/test",
  adminBlogSectionRevisions: (id: string) => `/api/tools/admin/blog/posts/${encodeURIComponent(id)}/section-revisions`,
  adminBlogSectionRegeneration: (id: string) => `/api/tools/admin/blog/posts/${encodeURIComponent(id)}/section-regeneration`,
  adminBlogSectionRevisionDecision: (id: string) => `/api/tools/admin/blog/section-revisions/${encodeURIComponent(id)}/decision`,
  adminBlogSources: "/api/tools/admin/blog/sources",
  adminBlogSource: (id: string) => `/api/tools/admin/blog/sources/${encodeURIComponent(id)}`,
  adminBlogSourceTest: (id: string) => `/api/tools/admin/blog/sources/${encodeURIComponent(id)}/test`,
  adminBlogTrendAction: (id: string) => `/api/tools/admin/blog/trends/${encodeURIComponent(id)}/action`,
  adminBlogOperations: "/api/tools/admin/blog/operations",
  adminBlogOperationAction: "/api/tools/admin/blog/operations/action",
};
