// Generated by npm run build:vercel-api. Do not edit by hand.
var __defProp = Object.defineProperty;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __esm = (fn, res, err) => function __init() {
  if (err) throw err[0];
  try {
    return fn && (res = (0, fn[__getOwnPropNames(fn)[0]])(fn = 0)), res;
  } catch (e) {
    throw err = [e], e;
  }
};
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};

// src/lib/seo/url-utils.ts
function isPrivateHostname(hostname) {
  const lower = hostname.toLowerCase();
  if (lower === "localhost" || lower.endsWith(".local")) return true;
  if (/^10\./.test(lower)) return true;
  if (/^127\./.test(lower)) return true;
  if (/^169\.254\./.test(lower)) return true;
  if (/^192\.168\./.test(lower)) return true;
  if (/^172\.(1[6-9]|2\d|3[0-1])\./.test(lower)) return true;
  if (lower === "::1" || lower.startsWith("fc") || lower.startsWith("fd")) return true;
  return false;
}
function hasLikelyRegistrableHost(hostname) {
  if (/^\d{1,3}(?:\.\d{1,3}){3}$/.test(hostname)) return true;
  if (!hostname || hostname.startsWith(".") || hostname.endsWith(".")) return false;
  if (!hostname.includes(".")) return false;
  const labels = hostname.split(".");
  const tld = labels[labels.length - 1];
  return labels.every(Boolean) && /^[a-z0-9-]+$/i.test(tld) && tld.length >= 2;
}
function normalizeUserUrl(input) {
  const trimmed = input.trim();
  if (!trimmed) {
    return {
      input: trimmed,
      normalizedUrl: "",
      origin: "",
      hostname: "",
      protocol: "https:",
      pathname: "",
      isValid: false,
      error: "URL is required"
    };
  }
  if (BLOCKED_PROTOCOLS.some((protocol) => trimmed.toLowerCase().startsWith(protocol))) {
    return {
      input: trimmed,
      normalizedUrl: "",
      origin: "",
      hostname: "",
      protocol: "https:",
      pathname: "",
      isValid: false,
      error: "Only HTTP and HTTPS URLs are supported"
    };
  }
  let withProtocol = trimmed;
  if (!/^[a-z][a-z0-9+.-]*:\/\//i.test(trimmed)) {
    withProtocol = `https://${trimmed}`;
  }
  try {
    const parsed = new URL(withProtocol);
    if (parsed.protocol !== "http:" && parsed.protocol !== "https:") {
      throw new Error("Only HTTP and HTTPS URLs are supported");
    }
    if (!hasLikelyRegistrableHost(parsed.hostname)) {
      throw new Error("Enter a valid public domain");
    }
    if (typeof process !== "undefined" && process.env.NODE_ENV === "production" && isPrivateHostname(parsed.hostname)) {
      throw new Error("Private and localhost targets are not allowed in production");
    }
    parsed.hash = "";
    parsed.username = "";
    parsed.password = "";
    return {
      input: trimmed,
      normalizedUrl: parsed.href,
      origin: parsed.origin,
      hostname: parsed.hostname,
      protocol: parsed.protocol,
      pathname: parsed.pathname,
      isValid: true
    };
  } catch (error) {
    return {
      input: trimmed,
      normalizedUrl: "",
      origin: "",
      hostname: "",
      protocol: "https:",
      pathname: "",
      isValid: false,
      error: error.message || "Invalid URL"
    };
  }
}
var BLOCKED_PROTOCOLS;
var init_url_utils = __esm({
  "src/lib/seo/url-utils.ts"() {
    BLOCKED_PROTOCOLS = ["javascript:", "data:", "file:", "ftp:"];
  }
});

// src/lib/keywords/intent.ts
function classifyIntent(keyword) {
  const normalized = keyword.toLowerCase();
  const informational = ["how", "what", "why", "guide", "tips", "tutorial", "learn", "examples", "ideas", "ways"];
  const commercial = ["best", "top", "review", "compare", "vs", "versus", "alternatives"];
  const transactional = ["buy", "price", "cost", "hire", "service", "near me", "cheap", "coupon", "discount", "software"];
  const navigational = ["login", "sign in", "app", "dashboard"];
  if (navigational.some((word) => normalized.includes(word))) return "Navigational";
  if (transactional.some((word) => normalized.includes(word))) return "Transactional";
  if (commercial.some((word) => normalized.includes(word))) return "Commercial";
  if (informational.some((word) => normalized.includes(word))) return "Informational";
  return "Informational";
}
function getFunnelStage(intent) {
  switch (intent) {
    case "Navigational":
      return "Awareness";
    case "Informational":
      return "Awareness";
    case "Commercial":
      return "Consideration";
    case "Transactional":
      return "Decision";
    default:
      return "Awareness";
  }
}
var init_intent = __esm({
  "src/lib/keywords/intent.ts"() {
  }
});

// src/lib/keywords/difficulty.ts
function estimateDifficulty(keyword) {
  let score = 50;
  const words = keyword.trim().split(/\s+/).length;
  if (words >= 4) score -= 15;
  if (words >= 6) score -= 10;
  if (words === 1) score += 20;
  if (words === 2) score += 10;
  const normalized = keyword.toLowerCase();
  const highComp = ["best", "top", "software", "service", "buy", "hire"];
  if (highComp.some((w) => normalized.includes(w))) {
    score += 15;
  }
  return Math.min(Math.max(Math.round(score), 0), 100);
}
var init_difficulty = __esm({
  "src/lib/keywords/difficulty.ts"() {
  }
});

// src/lib/keywords/opportunity.ts
function calculateOpportunityScore(keyword, relevance = 70, importedVolume, importedDifficulty) {
  const intent = classifyIntent(keyword);
  let intentValue = 50;
  if (intent === "Transactional") intentValue = 100;
  if (intent === "Commercial") intentValue = 80;
  if (intent === "Informational") intentValue = 60;
  const words = keyword.trim().split(/\s+/).length;
  const longTailScore = words >= 4 ? 100 : words === 3 ? 70 : 40;
  let volumeScore = 50;
  if (importedVolume) {
    if (importedVolume > 1e4) volumeScore = 100;
    else if (importedVolume > 1e3) volumeScore = 80;
    else if (importedVolume > 100) volumeScore = 60;
    else volumeScore = 30;
  }
  const difficulty = importedDifficulty ?? estimateDifficulty(keyword);
  const difficultyPenalty = difficulty * 0.5;
  let score = 0;
  if (importedVolume) {
    score = relevance * 0.35 + intentValue * 0.2 + longTailScore * 0.15 + volumeScore * 0.3 - difficultyPenalty;
  } else {
    score = relevance * 0.5 + intentValue * 0.3 + longTailScore * 0.2 - difficultyPenalty;
  }
  return Math.min(Math.max(Math.round(score), 0), 100);
}
var init_opportunity = __esm({
  "src/lib/keywords/opportunity.ts"() {
    init_intent();
    init_difficulty();
  }
});

// src/lib/keywords/generator.ts
function generateKeywords(seed) {
  const normalizedSeed = seed.toLowerCase().trim();
  const results = [];
  let idCounter = 1;
  const addResult = (kw, source, rel = 70) => {
    if (!kw || kw.trim() === "") return;
    const diff = estimateDifficulty(kw);
    const intent = classifyIntent(kw);
    let contentType = "Blog Post";
    if (intent === "Transactional") contentType = "Service/Product Page";
    if (intent === "Commercial") contentType = "Comparison/Review Page";
    results.push({
      id: String(idCounter++),
      keyword: kw,
      intent,
      funnelStage: getFunnelStage(intent),
      relevanceScore: rel,
      estimatedDifficulty: diff,
      opportunityScore: calculateOpportunityScore(kw, rel),
      suggestedContentType: contentType,
      source
    });
  };
  const prefixes = {
    questions: ["what is", "how to", "why", "when", "where", "who", "is", "can", "do", "are"],
    commercial: ["best", "top", "affordable", "cheap", "custom", "professional", "expert", "reliable", "certified"],
    transactional: ["buy", "hire", "find", "get", "order", "download"],
    local: ["local"],
    comparisons: ["best"],
    industry: ["for small business", "for startups", "for enterprise", "for beginners"]
  };
  const suffixes = {
    questions: ["explained", "definition", "meaning"],
    commercial: ["services", "software", "tools", "agency", "company", "consultant", "experts", "platform", "app"],
    transactional: ["price", "cost", "pricing", "quote", "packages"],
    local: ["near me", "in my area", "nearby"],
    comparisons: ["alternatives", "competitors", "vs", "compared", "reviews", "pros and cons"],
    problem: ["mistakes", "issues", "problems", "challenges", "examples"],
    resources: ["template", "checklist", "calculator", "guide", "pdf", "tutorial"]
  };
  addResult(normalizedSeed, "Seed", 100);
  for (const p of prefixes.questions) addResult(`${p} ${normalizedSeed}`, "Question Modifier", 85);
  for (const p of prefixes.commercial) addResult(`${p} ${normalizedSeed}`, "Commercial Modifier", 80);
  for (const p of prefixes.transactional) addResult(`${p} ${normalizedSeed}`, "Transactional Modifier", 80);
  for (const s of suffixes.commercial) addResult(`${normalizedSeed} ${s}`, "Commercial Modifier", 80);
  for (const s of suffixes.transactional) addResult(`${normalizedSeed} ${s}`, "Transactional Modifier", 85);
  for (const s of suffixes.local) addResult(`${normalizedSeed} ${s}`, "Local Modifier", 75);
  for (const s of suffixes.comparisons) {
    if (s === "vs") {
      addResult(`${normalizedSeed} vs alternative`, "Comparison Modifier", 70);
    } else {
      addResult(`${normalizedSeed} ${s}`, "Comparison Modifier", 70);
    }
  }
  for (const s of suffixes.problem) addResult(`${normalizedSeed} ${s}`, "Problem/Solution Modifier", 85);
  for (const s of suffixes.resources) addResult(`${normalizedSeed} ${s}`, "Resource Modifier", 85);
  for (const s of prefixes.industry) addResult(`${normalizedSeed} ${s}`, "Industry Modifier", 75);
  const alphabet = "abcdefghijklmnopqrstuvwxyz".split("");
  for (const letter of alphabet) {
    addResult(`${normalizedSeed} ${letter}`, "Alphabet Expansion", 60);
  }
  const uniqueResults = Array.from(new Map(results.map((item) => [item.keyword, item])).values());
  return uniqueResults;
}
var init_generator = __esm({
  "src/lib/keywords/generator.ts"() {
    init_intent();
    init_difficulty();
    init_opportunity();
  }
});

// src/lib/keywords/stopwords.ts
function removeStopwords(text) {
  return text.split(/\s+/).filter((word) => !STOPWORDS.has(word.toLowerCase())).join(" ");
}
var STOPWORDS;
var init_stopwords = __esm({
  "src/lib/keywords/stopwords.ts"() {
    STOPWORDS = /* @__PURE__ */ new Set([
      "a",
      "about",
      "above",
      "after",
      "again",
      "against",
      "all",
      "am",
      "an",
      "and",
      "any",
      "are",
      "aren't",
      "as",
      "at",
      "be",
      "because",
      "been",
      "before",
      "being",
      "below",
      "between",
      "both",
      "but",
      "by",
      "can't",
      "cannot",
      "could",
      "couldn't",
      "did",
      "didn't",
      "do",
      "does",
      "doesn't",
      "doing",
      "don't",
      "down",
      "during",
      "each",
      "few",
      "for",
      "from",
      "further",
      "had",
      "hadn't",
      "has",
      "hasn't",
      "have",
      "haven't",
      "having",
      "he",
      "he'd",
      "he'll",
      "he's",
      "her",
      "here",
      "here's",
      "hers",
      "herself",
      "him",
      "himself",
      "his",
      "how",
      "how's",
      "i",
      "i'd",
      "i'll",
      "i'm",
      "i've",
      "if",
      "in",
      "into",
      "is",
      "isn't",
      "it",
      "it's",
      "its",
      "itself",
      "let's",
      "me",
      "more",
      "most",
      "mustn't",
      "my",
      "myself",
      "no",
      "nor",
      "not",
      "of",
      "off",
      "on",
      "once",
      "only",
      "or",
      "other",
      "ought",
      "our",
      "ours",
      "ourselves",
      "out",
      "over",
      "own",
      "same",
      "shan't",
      "she",
      "she'd",
      "she'll",
      "she's",
      "should",
      "shouldn't",
      "so",
      "some",
      "such",
      "than",
      "that",
      "that's",
      "the",
      "their",
      "theirs",
      "them",
      "themselves",
      "then",
      "there",
      "there's",
      "these",
      "they",
      "they'd",
      "they'll",
      "they're",
      "they've",
      "this",
      "those",
      "through",
      "to",
      "too",
      "under",
      "until",
      "up",
      "very",
      "was",
      "wasn't",
      "we",
      "we'd",
      "we'll",
      "we're",
      "we've",
      "were",
      "weren't",
      "what",
      "what's",
      "when",
      "when's",
      "where",
      "where's",
      "which",
      "while",
      "who",
      "who's",
      "whom",
      "why",
      "why's",
      "with",
      "won't",
      "would",
      "wouldn't",
      "you",
      "you'd",
      "you'll",
      "you're",
      "you've",
      "your",
      "yours",
      "yourself",
      "yourselves"
    ]);
  }
});

// src/lib/keywords/clustering.ts
function jaccardSimilarity(str1, str2) {
  const set1 = new Set(str1.split(/\s+/));
  const set2 = new Set(str2.split(/\s+/));
  const intersection = new Set([...set1].filter((x) => set2.has(x)));
  const union = /* @__PURE__ */ new Set([...set1, ...set2]);
  return intersection.size / union.size;
}
function clusterKeywords(keywords) {
  const clusters = [];
  const processed = /* @__PURE__ */ new Set();
  for (const kw of keywords) {
    if (processed.has(kw.keyword)) continue;
    const currentCluster = [kw.keyword];
    processed.add(kw.keyword);
    const kwClean = removeStopwords(kw.keyword.toLowerCase());
    for (const other of keywords) {
      if (processed.has(other.keyword)) continue;
      const otherClean = removeStopwords(other.keyword.toLowerCase());
      if (jaccardSimilarity(kwClean, otherClean) > 0.4 || kwClean.includes(otherClean) || otherClean.includes(kwClean)) {
        currentCluster.push(other.keyword);
        processed.add(other.keyword);
      }
    }
    const primary = currentCluster.reduce((a, b) => a.length <= b.length ? a : b);
    const primaryResult = keywords.find((k) => k.keyword === primary) || kw;
    const clusterResults = keywords.filter((k) => currentCluster.includes(k.keyword));
    const avgOpp = clusterResults.reduce((sum, k) => sum + k.opportunityScore, 0) / currentCluster.length;
    const avgDiff = clusterResults.reduce((sum, k) => sum + k.estimatedDifficulty, 0) / currentCluster.length;
    clusters.push({
      id: `cluster-${clusters.length + 1}`,
      name: primary,
      primaryKeyword: primary,
      keywords: currentCluster.filter((k) => k !== primary),
      intent: primaryResult.intent,
      opportunityScore: Math.round(avgOpp),
      difficulty: Math.round(avgDiff),
      suggestedContentType: primaryResult.suggestedContentType
    });
  }
  return clusters;
}
var init_clustering = __esm({
  "src/lib/keywords/clustering.ts"() {
    init_stopwords();
  }
});

// src/lib/keywords/content-brief.ts
function buildContentBrief(cluster) {
  const primary = cluster.primaryKeyword;
  const capitalized = primary.split(" ").map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(" ");
  const brief = {
    titleTemplates: [],
    metaDescriptionTemplates: [],
    h1Suggestions: [],
    h2Outline: [],
    faqs: [],
    relatedKeywords: cluster.keywords,
    targetIntent: cluster.intent,
    suggestedFormat: cluster.suggestedContentType,
    wordCount: "1000 - 1500 words"
  };
  if (cluster.intent === "Informational") {
    brief.titleTemplates = [
      `What is ${capitalized}? A Complete Guide`,
      `The Ultimate Guide to ${capitalized} in ${(/* @__PURE__ */ new Date()).getFullYear()}`
    ];
    brief.metaDescriptionTemplates = [
      `Learn everything you need to know about ${primary}. Discover how it works, benefits, and common mistakes to avoid.`
    ];
    brief.h1Suggestions = [`What is ${capitalized}?`, `Complete Guide to ${capitalized}`];
    brief.h2Outline = [
      `Introduction to ${capitalized}`,
      `How ${capitalized} Works`,
      `Key Benefits of ${capitalized}`,
      `Common Mistakes to Avoid`,
      `Conclusion`
    ];
    brief.faqs = [
      `What is the main purpose of ${primary}?`,
      `How do I get started with ${primary}?`,
      `Is ${primary} worth the investment?`
    ];
  } else if (cluster.intent === "Commercial") {
    brief.titleTemplates = [
      `Best ${capitalized} Services in ${(/* @__PURE__ */ new Date()).getFullYear()}`,
      `Top 10 ${capitalized} Options Compared`
    ];
    brief.metaDescriptionTemplates = [
      `Comparing the best ${primary} options? Read our comprehensive review to find the perfect fit for your needs and budget.`
    ];
    brief.h1Suggestions = [`Best ${capitalized} Options`, `Comparing ${capitalized} Services`];
    brief.h2Outline = [
      `Top ${capitalized} Reviews`,
      `Comparison Table`,
      `Key Features to Look For`,
      `Pricing Guide`,
      `Final Verdict`
    ];
    brief.faqs = [
      `Which ${primary} is the best overall?`,
      `How much does ${primary} typically cost?`,
      `What are the alternatives to ${primary}?`
    ];
  } else if (cluster.intent === "Transactional") {
    brief.titleTemplates = [
      `${capitalized} Services - Expert Help`,
      `Affordable ${capitalized} Near You`
    ];
    brief.metaDescriptionTemplates = [
      `Need professional ${primary}? We offer expert services at competitive prices. Contact us today for a free quote.`
    ];
    brief.h1Suggestions = [`Professional ${capitalized} Services`, `Expert ${capitalized}`];
    brief.h2Outline = [
      `Our ${capitalized} Services`,
      `Why Choose Us for ${capitalized}?`,
      `Pricing Plans`,
      `Client Testimonials`,
      `Get a Free Quote`
    ];
    brief.faqs = [
      `How long does the ${primary} process take?`,
      `What is included in your ${primary} service?`,
      `Do you offer guarantees for ${primary}?`
    ];
    brief.wordCount = "500 - 800 words";
  } else {
    brief.titleTemplates = [`${capitalized}`];
    brief.metaDescriptionTemplates = [`Official page for ${primary}.`];
    brief.h1Suggestions = [`${capitalized}`];
    brief.h2Outline = [`About ${capitalized}`];
    brief.faqs = [];
    brief.wordCount = "300 - 500 words";
  }
  return brief;
}
var init_content_brief = __esm({
  "src/lib/keywords/content-brief.ts"() {
  }
});

// src/lib/audit/audit-store.ts
var jobs, eventsStore, subscriptions, auditStore;
var init_audit_store = __esm({
  "src/lib/audit/audit-store.ts"() {
    jobs = /* @__PURE__ */ new Map();
    eventsStore = /* @__PURE__ */ new Map();
    subscriptions = /* @__PURE__ */ new Map();
    auditStore = {
      createAudit(input) {
        const id = Math.random().toString(36).substring(2, 15) + Date.now().toString(36);
        const newJob = {
          id,
          jobId: id,
          url: input.url,
          type: input.type,
          status: "queued",
          progress: 0,
          currentStep: "Initializing",
          pagesDiscovered: 0,
          pagesCrawled: 0,
          checksTotal: 0,
          checksCompleted: 0,
          issuesFound: 0,
          startedAt: (/* @__PURE__ */ new Date()).toISOString()
        };
        jobs.set(id, newJob);
        eventsStore.set(id, []);
        subscriptions.set(id, /* @__PURE__ */ new Set());
        this.appendAuditEvent(id, {
          type: "audit_queued",
          message: "Audit added to queue",
          progress: 0
        });
        return id;
      },
      createJob(targetUrl) {
        return this.createAudit({ url: targetUrl, type: "seo" });
      },
      getAudit(id) {
        return jobs.get(id);
      },
      getJob(id) {
        return jobs.get(id);
      },
      updateAudit(id, patch) {
        const job = jobs.get(id);
        if (job) {
          jobs.set(id, { ...job, ...patch });
        }
      },
      updateJob(id, patch) {
        this.updateAudit(id, patch);
      },
      appendAuditEvent(id, eventData) {
        const job = jobs.get(id);
        if (!job) return;
        const event = {
          id: Math.random().toString(36).substring(2, 15),
          auditId: id,
          type: eventData.type || "audit_warning",
          timestamp: (/* @__PURE__ */ new Date()).toISOString(),
          message: eventData.message || "",
          progress: eventData.progress ?? (job.progress || 0),
          step: eventData.step || job.currentStep,
          pagesDiscovered: eventData.pagesDiscovered ?? job.pagesDiscovered,
          pagesCrawled: eventData.pagesCrawled ?? job.pagesCrawled,
          checksTotal: eventData.checksTotal ?? job.checksTotal,
          checksCompleted: eventData.checksCompleted ?? (eventData.type === "check_completed" ? (job.checksCompleted || 0) + 1 : job.checksCompleted),
          issuesFound: eventData.issuesFound ?? (eventData.type === "issue_found" ? (job.issuesFound || 0) + 1 : job.issuesFound),
          ...eventData
        };
        this.updateAudit(id, {
          progress: event.progress,
          currentStep: event.step,
          pagesDiscovered: event.pagesDiscovered,
          pagesCrawled: event.pagesCrawled,
          checksTotal: event.checksTotal,
          checksCompleted: event.checksCompleted,
          issuesFound: event.issuesFound,
          ...event.type === "audit_started" ? { status: "running" } : {},
          ...event.type === "audit_completed" ? { status: "completed" } : {},
          ...event.type === "audit_failed" ? { status: "failed", error: event.message } : {}
        });
        const events = eventsStore.get(id) || [];
        events.push(event);
        if (events.length > 500) {
          events.shift();
        }
        const subs = subscriptions.get(id);
        if (subs) {
          subs.forEach((cb) => {
            try {
              cb(event);
            } catch (err) {
            }
          });
        }
      },
      getAuditEvents(id) {
        return eventsStore.get(id) || [];
      },
      subscribeToAudit(id, callback) {
        let subs = subscriptions.get(id);
        if (!subs) {
          subs = /* @__PURE__ */ new Set();
          subscriptions.set(id, subs);
        }
        subs.add(callback);
      },
      unsubscribeFromAudit(id, callback) {
        const subs = subscriptions.get(id);
        if (subs) {
          subs.delete(callback);
        }
      },
      getAllJobs() {
        return Array.from(jobs.values()).sort((a, b) => new Date(b.startedAt).getTime() - new Date(a.startedAt).getTime());
      }
    };
  }
});

// src/lib/audit/audit-config.ts
function getAuditModeConfig(mode) {
  if (mode === "standard" || mode === "deep") {
    return AUDIT_MODE_CONFIG[mode];
  }
  return AUDIT_MODE_CONFIG.quick;
}
var AUDIT_MODE_CONFIG, AUDIT_LIMITS;
var init_audit_config = __esm({
  "src/lib/audit/audit-config.ts"() {
    AUDIT_MODE_CONFIG = {
      quick: {
        mode: "quick",
        label: "Quick - 10 pages",
        pageLimit: 10,
        concurrency: 2,
        timeoutMs: 6e3,
        description: "Default resource-light audit for fast feedback."
      },
      standard: {
        mode: "standard",
        label: "Standard - 25 pages",
        pageLimit: 25,
        concurrency: 3,
        timeoutMs: 8e3,
        description: "Balanced crawl depth and resource use."
      },
      deep: {
        mode: "deep",
        label: "Deep - 50 pages",
        pageLimit: 50,
        concurrency: 3,
        timeoutMs: 1e4,
        description: "Manual opt-in audit for broader coverage."
      }
    };
    AUDIT_LIMITS = {
      maxEvents: 300,
      maxIssues: 1e3,
      lockLeaseMs: 5 * 60 * 1e3,
      staleLockRecoveryMs: 5 * 60 * 1e3,
      defaultExpiresInDays: 30,
      workerPollIntervalMs: 4e3,
      livePollIntervalMs: 2e3,
      noWorkerWarningMs: 2e4
    };
  }
});

// src/lib/audit/resource-types.ts
var init_resource_types = __esm({
  "src/lib/audit/resource-types.ts"() {
    init_audit_config();
  }
});

// src/lib/supabase/url.ts
function normalizeSupabaseProjectUrl(value) {
  const trimmed = value?.trim();
  if (!trimmed) return "";
  try {
    return new URL(trimmed).origin;
  } catch {
    return trimmed.replace(/\/+$/, "");
  }
}
var init_url = __esm({
  "src/lib/supabase/url.ts"() {
  }
});

// src/lib/supabase/server.ts
import { createClient } from "@supabase/supabase-js";
function hasSupabaseServerConfig() {
  return Boolean(normalizeSupabaseProjectUrl(process.env.SUPABASE_URL) && process.env.SUPABASE_SERVICE_ROLE_KEY);
}
function isSupabaseAdminEnabled() {
  return hasSupabaseServerConfig();
}
function getSupabaseProjectHostname() {
  const supabaseUrl = normalizeSupabaseProjectUrl(process.env.SUPABASE_URL);
  if (!supabaseUrl) return null;
  try {
    return new URL(supabaseUrl).hostname;
  } catch {
    return null;
  }
}
function getSupabaseAdminClient() {
  if (!hasSupabaseServerConfig()) {
    return null;
  }
  if (cachedClient === void 0) {
    const supabaseUrl = normalizeSupabaseProjectUrl(process.env.SUPABASE_URL);
    cachedClient = createClient(
      supabaseUrl,
      process.env.SUPABASE_SERVICE_ROLE_KEY,
      {
        auth: {
          autoRefreshToken: false,
          persistSession: false
        }
      }
    );
  }
  return cachedClient;
}
function requireSupabaseAdminClient(message = "Supabase admin client is required for this operation.") {
  const client = getSupabaseAdminClient();
  if (!client) {
    throw new Error(message);
  }
  return client;
}
var cachedClient;
var init_server = __esm({
  "src/lib/supabase/server.ts"() {
    init_url();
  }
});

// src/lib/supabase/audit-repository.ts
import { createHash, randomUUID } from "node:crypto";
function nowIso() {
  return (/* @__PURE__ */ new Date()).toISOString();
}
function expiresAtIso() {
  const date = /* @__PURE__ */ new Date();
  date.setDate(date.getDate() + AUDIT_LIMITS.defaultExpiresInDays);
  return date.toISOString();
}
function pageIdForAuditUrl(auditId, url) {
  return createHash("sha256").update(`${auditId}:${url}`).digest("hex").slice(0, 40);
}
function workerHeartbeatKey(workerId) {
  return `audit_worker:${workerId}`;
}
function isClaimableLock(row, timestamp) {
  if (!row.locked_by) return true;
  if (!row.lease_expires_at) return true;
  return String(row.lease_expires_at) <= timestamp;
}
function isStaleRunningLock(row, timestamp) {
  if (!row.lease_expires_at) return true;
  return String(row.lease_expires_at) <= timestamp;
}
function toWorkerHeartbeat(row) {
  const value = row.value ?? {};
  const fallbackWorkerId = String(row.id || "").replace(/^audit_worker:/, "") || "unknown";
  return {
    workerId: String(value.workerId || fallbackWorkerId),
    status: value.status || "failed",
    lastSeenAt: String(value.lastSeenAt || row.updated_at || nowIso()),
    pollIntervalMs: Number(value.pollIntervalMs || 0),
    currentAuditId: value.currentAuditId ?? null,
    version: String(value.version || "unknown"),
    runtime: value.runtime || void 0,
    supportedModes: Array.isArray(value.supportedModes) ? value.supportedModes : void 0,
    deepAuditEnabled: typeof value.deepAuditEnabled === "boolean" ? value.deepAuditEnabled : void 0
  };
}
function assertNoError(error, action) {
  if (error) {
    throw new Error(`${action}: ${error.message || "Unknown Supabase error"}`);
  }
}
function toAuditDocument(row) {
  if (!row) return null;
  return {
    id: row.id,
    userId: row.user_id ?? null,
    guestKeyHash: row.guest_key_hash ?? null,
    projectId: row.project_id ?? null,
    submittedInput: row.submitted_input,
    normalizedUrl: row.normalized_url,
    finalUrl: row.final_url ?? null,
    hostname: row.hostname,
    mode: row.mode,
    plan: row.plan ?? "free",
    requestedMode: row.requested_mode ?? row.mode ?? "quick",
    effectiveMode: row.effective_mode ?? row.mode ?? "quick",
    queuePriority: row.queue_priority ?? 10,
    processingTier: row.processing_tier ?? row.plan ?? "free",
    quotaCounted: row.quota_counted ?? false,
    workerRuntime: row.worker_runtime ?? null,
    estimatedWaitSeconds: row.estimated_wait_seconds ?? null,
    status: row.status,
    progress: row.progress ?? 0,
    currentPhase: row.current_phase ?? "Queued",
    currentUrl: row.current_url ?? null,
    currentCheck: row.current_check ?? null,
    pageLimit: row.page_limit ?? 0,
    pagesDiscovered: row.pages_discovered ?? 0,
    pagesCrawled: row.pages_crawled ?? 0,
    checksTotal: row.checks_total ?? 0,
    checksCompleted: row.checks_completed ?? 0,
    issuesFound: row.issues_found ?? 0,
    criticalCount: row.critical_count ?? 0,
    highCount: row.high_count ?? 0,
    mediumCount: row.medium_count ?? 0,
    lowCount: row.low_count ?? 0,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    startedAt: row.started_at ?? null,
    completedAt: row.completed_at ?? null,
    expiresAt: row.expires_at,
    cancelledAt: row.cancelled_at ?? null,
    error: row.error ?? null,
    lockedBy: row.locked_by ?? null,
    lockedAt: row.locked_at ?? null,
    leaseExpiresAt: row.lease_expires_at ?? null,
    usedHttpFallback: row.used_http_fallback ?? void 0
  };
}
function auditToRow(audit) {
  return {
    id: audit.id,
    user_id: audit.userId,
    guest_key_hash: audit.guestKeyHash,
    project_id: audit.projectId,
    submitted_input: audit.submittedInput,
    normalized_url: audit.normalizedUrl,
    final_url: audit.finalUrl,
    hostname: audit.hostname,
    mode: audit.mode,
    plan: audit.plan ?? "free",
    requested_mode: audit.requestedMode ?? audit.mode,
    effective_mode: audit.effectiveMode ?? audit.mode,
    queue_priority: audit.queuePriority ?? 10,
    processing_tier: audit.processingTier ?? audit.plan ?? "free",
    quota_counted: audit.quotaCounted ?? false,
    worker_runtime: audit.workerRuntime,
    estimated_wait_seconds: audit.estimatedWaitSeconds,
    status: audit.status,
    progress: audit.progress,
    current_phase: audit.currentPhase,
    current_url: audit.currentUrl,
    current_check: audit.currentCheck,
    page_limit: audit.pageLimit,
    pages_discovered: audit.pagesDiscovered,
    pages_crawled: audit.pagesCrawled,
    checks_total: audit.checksTotal,
    checks_completed: audit.checksCompleted,
    issues_found: audit.issuesFound,
    critical_count: audit.criticalCount,
    high_count: audit.highCount,
    medium_count: audit.mediumCount,
    low_count: audit.lowCount,
    created_at: audit.createdAt,
    updated_at: audit.updatedAt,
    started_at: audit.startedAt,
    completed_at: audit.completedAt,
    expires_at: audit.expiresAt,
    cancelled_at: audit.cancelledAt,
    error: audit.error,
    locked_by: audit.lockedBy,
    locked_at: audit.lockedAt,
    lease_expires_at: audit.leaseExpiresAt,
    used_http_fallback: audit.usedHttpFallback ?? false
  };
}
function auditPatchToRow(patch) {
  const row = { updated_at: nowIso() };
  if ("userId" in patch) row.user_id = patch.userId;
  if ("guestKeyHash" in patch) row.guest_key_hash = patch.guestKeyHash;
  if ("projectId" in patch) row.project_id = patch.projectId;
  if ("submittedInput" in patch) row.submitted_input = patch.submittedInput;
  if ("normalizedUrl" in patch) row.normalized_url = patch.normalizedUrl;
  if ("finalUrl" in patch) row.final_url = patch.finalUrl;
  if ("hostname" in patch) row.hostname = patch.hostname;
  if ("mode" in patch) row.mode = patch.mode;
  if ("plan" in patch) row.plan = patch.plan;
  if ("requestedMode" in patch) row.requested_mode = patch.requestedMode;
  if ("effectiveMode" in patch) row.effective_mode = patch.effectiveMode;
  if ("queuePriority" in patch) row.queue_priority = patch.queuePriority;
  if ("processingTier" in patch) row.processing_tier = patch.processingTier;
  if ("quotaCounted" in patch) row.quota_counted = patch.quotaCounted;
  if ("workerRuntime" in patch) row.worker_runtime = patch.workerRuntime;
  if ("estimatedWaitSeconds" in patch) row.estimated_wait_seconds = patch.estimatedWaitSeconds;
  if ("status" in patch) row.status = patch.status;
  if ("progress" in patch) row.progress = patch.progress;
  if ("currentPhase" in patch) row.current_phase = patch.currentPhase;
  if ("currentUrl" in patch) row.current_url = patch.currentUrl;
  if ("currentCheck" in patch) row.current_check = patch.currentCheck;
  if ("pageLimit" in patch) row.page_limit = patch.pageLimit;
  if ("pagesDiscovered" in patch) row.pages_discovered = patch.pagesDiscovered;
  if ("pagesCrawled" in patch) row.pages_crawled = patch.pagesCrawled;
  if ("checksTotal" in patch) row.checks_total = patch.checksTotal;
  if ("checksCompleted" in patch) row.checks_completed = patch.checksCompleted;
  if ("issuesFound" in patch) row.issues_found = patch.issuesFound;
  if ("criticalCount" in patch) row.critical_count = patch.criticalCount;
  if ("highCount" in patch) row.high_count = patch.highCount;
  if ("mediumCount" in patch) row.medium_count = patch.mediumCount;
  if ("lowCount" in patch) row.low_count = patch.lowCount;
  if ("completedAt" in patch) row.completed_at = patch.completedAt;
  if ("startedAt" in patch) row.started_at = patch.startedAt;
  if ("expiresAt" in patch) row.expires_at = patch.expiresAt;
  if ("cancelledAt" in patch) row.cancelled_at = patch.cancelledAt;
  if ("error" in patch) row.error = patch.error;
  if ("lockedBy" in patch) row.locked_by = patch.lockedBy;
  if ("lockedAt" in patch) row.locked_at = patch.lockedAt;
  if ("leaseExpiresAt" in patch) row.lease_expires_at = patch.leaseExpiresAt;
  if ("usedHttpFallback" in patch) row.used_http_fallback = patch.usedHttpFallback;
  return row;
}
function toAuditEvent(row) {
  return {
    id: row.id,
    type: row.type,
    timestamp: row.created_at,
    message: row.message ?? "",
    phase: row.phase ?? void 0,
    currentUrl: row.current_url ?? void 0,
    affectedUrl: row.affected_url ?? void 0,
    category: row.category ?? void 0,
    checkId: row.check_id ?? void 0,
    checkTitle: row.check_title ?? void 0,
    severity: row.severity ?? void 0,
    progress: row.progress ?? void 0,
    data: row.data ?? void 0
  };
}
function eventToRow(auditId, event) {
  return {
    id: event.id,
    audit_id: auditId,
    type: event.type,
    created_at: event.timestamp,
    message: event.message,
    phase: event.phase,
    current_url: event.currentUrl,
    affected_url: event.affectedUrl,
    category: event.category,
    check_id: event.checkId,
    check_title: event.checkTitle,
    severity: event.severity,
    progress: event.progress,
    data: event.data ?? null
  };
}
function toAuditPage(row) {
  return {
    id: row.id,
    url: row.url,
    statusCode: row.status_code ?? 0,
    responseTimeMs: row.response_time_ms ?? 0,
    pageSizeBytes: row.page_size_bytes ?? 0,
    title: row.title ?? "",
    metaDescription: row.meta_description ?? "",
    h1: row.h1 ?? "",
    wordCount: row.word_count ?? 0,
    crawlDepth: row.crawl_depth ?? 0,
    issueCount: row.issue_count ?? 0,
    crawledAt: row.crawled_at
  };
}
function pageToRow(auditId, page) {
  return {
    id: page.id,
    audit_id: auditId,
    url: page.url,
    status_code: page.statusCode,
    response_time_ms: page.responseTimeMs,
    page_size_bytes: page.pageSizeBytes,
    title: page.title,
    meta_description: page.metaDescription,
    h1: page.h1,
    word_count: page.wordCount,
    crawl_depth: page.crawlDepth,
    issue_count: page.issueCount,
    crawled_at: page.crawledAt
  };
}
function toAuditIssue(row) {
  return {
    id: row.id,
    severity: row.severity,
    category: row.category,
    title: row.title,
    description: row.description,
    affectedUrl: row.affected_url,
    evidence: row.evidence ?? "",
    recommendation: row.recommendation ?? "",
    detectedAt: row.detected_at
  };
}
function issueToRow(auditId, issue) {
  return {
    id: issue.id,
    audit_id: auditId,
    severity: issue.severity,
    category: issue.category,
    title: issue.title,
    description: issue.description,
    affected_url: issue.affectedUrl,
    evidence: issue.evidence,
    recommendation: issue.recommendation,
    detected_at: issue.detectedAt
  };
}
function toAuditReport(row) {
  if (!row) return null;
  return {
    scores: row.scores ?? {},
    summary: typeof row.summary === "string" ? row.summary : row.summary?.text ?? "",
    topIssues: row.top_issues ?? [],
    pages: row.pages ?? [],
    exports: row.exports ?? { json: "", issuesCsv: "", pagesCsv: "" },
    generatedAt: row.generated_at
  };
}
function reportToRow(auditId, report) {
  return {
    audit_id: auditId,
    scores: report.scores,
    summary: { text: report.summary },
    top_issues: report.topIssues,
    pages: report.pages,
    exports: report.exports,
    generated_at: report.generatedAt
  };
}
var memory, auditRepository;
var init_audit_repository = __esm({
  "src/lib/supabase/audit-repository.ts"() {
    init_resource_types();
    init_server();
    memory = {
      audits: /* @__PURE__ */ new Map(),
      events: /* @__PURE__ */ new Map(),
      pages: /* @__PURE__ */ new Map(),
      issues: /* @__PURE__ */ new Map(),
      reports: /* @__PURE__ */ new Map()
    };
    auditRepository = {
      isSupabaseEnabled() {
        return isSupabaseAdminEnabled();
      },
      isSupabaseAdminEnabled() {
        return isSupabaseAdminEnabled();
      },
      requireSupabaseAdminClient() {
        return requireSupabaseAdminClient();
      },
      async upsertWorkerHeartbeat(heartbeat) {
        const client = requireSupabaseAdminClient();
        const payload = {
          workerId: heartbeat.workerId,
          status: heartbeat.status,
          lastSeenAt: heartbeat.lastSeenAt || nowIso(),
          pollIntervalMs: heartbeat.pollIntervalMs,
          currentAuditId: heartbeat.currentAuditId ?? null,
          version: heartbeat.version || "unknown",
          runtime: heartbeat.runtime,
          supportedModes: heartbeat.supportedModes,
          deepAuditEnabled: heartbeat.deepAuditEnabled
        };
        const { error } = await client.from("platform_settings").upsert(
          {
            id: workerHeartbeatKey(payload.workerId),
            value: payload,
            updated_at: payload.lastSeenAt
          },
          { onConflict: "id" }
        );
        assertNoError(error, "Upsert worker heartbeat");
        return payload;
      },
      async getWorkerHeartbeats() {
        const client = requireSupabaseAdminClient();
        const { data, error } = await client.from("platform_settings").select("id,value,updated_at").like("id", "audit_worker:%").order("updated_at", { ascending: false });
        assertNoError(error, "Get worker heartbeats");
        return (data ?? []).map(toWorkerHeartbeat);
      },
      async getLatestAuditDiagnostics(limit = 5) {
        const client = requireSupabaseAdminClient();
        const { data, error } = await client.from("audits").select("id,status,submitted_input,normalized_url,current_phase,locked_by,lease_expires_at,plan,requested_mode,effective_mode,queue_priority,processing_tier,error,created_at,updated_at").order("created_at", { ascending: false }).limit(limit);
        assertNoError(error, "Get latest audit diagnostics");
        return data ?? [];
      },
      async createAuditJob(input) {
        const id = randomUUID();
        const config = getAuditModeConfig(input.effectiveMode || input.mode);
        const timestamp = nowIso();
        const effectiveMode = input.effectiveMode || config.mode;
        const requestedMode = input.requestedMode || input.mode || effectiveMode;
        const plan = input.plan || "free";
        const audit = {
          id,
          userId: input.userId ?? null,
          guestKeyHash: input.guestKeyHash ?? null,
          projectId: input.projectId ?? null,
          submittedInput: input.submittedInput,
          normalizedUrl: input.normalizedUrl,
          finalUrl: null,
          hostname: input.hostname,
          mode: effectiveMode,
          plan,
          requestedMode,
          effectiveMode,
          queuePriority: input.queuePriority ?? 10,
          processingTier: input.processingTier ?? plan,
          quotaCounted: false,
          workerRuntime: null,
          estimatedWaitSeconds: input.estimatedWaitSeconds ?? null,
          status: "queued",
          progress: 0,
          currentPhase: "Queued",
          currentUrl: null,
          currentCheck: null,
          pageLimit: input.pageLimit ?? config.pageLimit,
          pagesDiscovered: 0,
          pagesCrawled: 0,
          checksTotal: 0,
          checksCompleted: 0,
          issuesFound: 0,
          criticalCount: 0,
          highCount: 0,
          mediumCount: 0,
          lowCount: 0,
          createdAt: timestamp,
          updatedAt: timestamp,
          startedAt: null,
          completedAt: null,
          expiresAt: expiresAtIso(),
          cancelledAt: null,
          error: null,
          lockedBy: null,
          lockedAt: null,
          leaseExpiresAt: null
        };
        const client = getSupabaseAdminClient();
        if (client) {
          const { error } = await client.from("audits").insert(auditToRow(audit));
          assertNoError(error, "Create audit job");
        } else {
          memory.audits.set(id, audit);
          memory.events.set(id, []);
          memory.pages.set(id, []);
          memory.issues.set(id, []);
        }
        await this.appendAuditEvent(id, {
          type: "audit_queued",
          message: `Audit queued for ${input.hostname}`,
          phase: "Queued",
          progress: 0
        });
        return audit;
      },
      async findActiveDuplicateAudit(input) {
        const client = getSupabaseAdminClient();
        if (client) {
          let query = client.from("audits").select("*").eq("normalized_url", input.normalizedUrl).in("status", ["queued", "running"]).gte("created_at", input.createdAfterIso);
          if (input.userId) {
            query = query.eq("user_id", input.userId);
          } else if (input.guestKeyHash) {
            query = query.is("user_id", null).eq("guest_key_hash", input.guestKeyHash);
          } else {
            query = query.is("user_id", null).is("guest_key_hash", null);
          }
          const { data, error } = await query.order("created_at", { ascending: false }).limit(1).maybeSingle();
          assertNoError(error, "Find active duplicate audit");
          return toAuditDocument(data);
        }
        return Array.from(memory.audits.values()).filter((audit) => audit.normalizedUrl === input.normalizedUrl).filter((audit) => audit.status === "queued" || audit.status === "running").filter((audit) => audit.createdAt >= input.createdAfterIso).filter((audit) => {
          if (input.userId) return audit.userId === input.userId;
          return !audit.userId && (audit.guestKeyHash ?? null) === (input.guestKeyHash ?? null);
        }).sort((a, b) => b.createdAt.localeCompare(a.createdAt))[0] ?? null;
      },
      async findActiveAuditForOwner(input) {
        const client = getSupabaseAdminClient();
        if (client) {
          let query = client.from("audits").select("*").in("status", ["queued", "running"]);
          if (input.userId) {
            query = query.eq("user_id", input.userId);
          } else if (input.guestKeyHash) {
            query = query.is("user_id", null).eq("guest_key_hash", input.guestKeyHash);
          } else {
            query = query.is("user_id", null).is("guest_key_hash", null);
          }
          const { data, error } = await query.order("created_at", { ascending: false }).limit(1).maybeSingle();
          assertNoError(error, "Find active audit for owner");
          return toAuditDocument(data);
        }
        return Array.from(memory.audits.values()).filter((audit) => audit.status === "queued" || audit.status === "running").filter((audit) => {
          if (input.userId) return audit.userId === input.userId;
          return !audit.userId && (audit.guestKeyHash ?? null) === (input.guestKeyHash ?? null);
        }).sort((a, b) => b.createdAt.localeCompare(a.createdAt))[0] ?? null;
      },
      async getAuditJob(id) {
        const client = getSupabaseAdminClient();
        if (client) {
          const { data, error } = await client.from("audits").select("*").eq("id", id).maybeSingle();
          assertNoError(error, "Get audit job");
          return toAuditDocument(data);
        }
        return memory.audits.get(id) ?? null;
      },
      async getAudit(id) {
        return this.getAuditJob(id);
      },
      async updateAuditJob(id, patch) {
        const update = { ...patch, updatedAt: nowIso() };
        const client = getSupabaseAdminClient();
        if (client) {
          const { error } = await client.from("audits").update(auditPatchToRow(update)).eq("id", id);
          assertNoError(error, "Update audit job");
          return;
        }
        const current = memory.audits.get(id);
        if (current) {
          memory.audits.set(id, { ...current, ...update });
        }
      },
      async updateAudit(id, patch) {
        return this.updateAuditJob(id, patch);
      },
      async cancelAuditJob(id) {
        const timestamp = nowIso();
        await this.updateAuditJob(id, {
          status: "cancelled",
          cancelledAt: timestamp,
          completedAt: timestamp,
          currentPhase: "Cancelled by user",
          currentCheck: null,
          lockedBy: null,
          lockedAt: null,
          leaseExpiresAt: null
        });
        await this.appendAuditEvent(id, {
          type: "audit_cancelled",
          timestamp,
          message: "Audit cancelled by user",
          phase: "Cancelled by user"
        });
      },
      async cancelAudit(id) {
        return this.cancelAuditJob(id);
      },
      async appendAuditEvent(auditId, event) {
        const id = randomUUID();
        const audit = await this.getAuditJob(auditId);
        const fullEvent = {
          id,
          type: event.type || "progress_update",
          timestamp: event.timestamp || nowIso(),
          message: event.message || "",
          phase: event.phase,
          currentUrl: event.currentUrl,
          affectedUrl: event.affectedUrl,
          category: event.category,
          checkId: event.checkId,
          checkTitle: event.checkTitle,
          severity: event.severity,
          progress: event.progress ?? audit?.progress,
          data: event.data
        };
        const client = getSupabaseAdminClient();
        if (client) {
          const { error } = await client.from("audit_events").insert(eventToRow(auditId, fullEvent));
          assertNoError(error, "Append audit event");
          const countResult = await client.from("audit_events").select("id", { count: "exact", head: true }).eq("audit_id", auditId);
          assertNoError(countResult.error, "Count audit events");
          const overLimit = (countResult.count ?? 0) - AUDIT_LIMITS.maxEvents;
          if (overLimit > 0) {
            const { data: oldRows, error: oldRowsError } = await client.from("audit_events").select("id").eq("audit_id", auditId).order("created_at", { ascending: true }).limit(overLimit);
            assertNoError(oldRowsError, "Find old audit events");
            const ids = (oldRows ?? []).map((row) => row.id);
            if (ids.length) {
              const { error: deleteError } = await client.from("audit_events").delete().in("id", ids);
              assertNoError(deleteError, "Delete old audit events");
            }
          }
          return;
        }
        const events = memory.events.get(auditId) ?? [];
        events.push(fullEvent);
        memory.events.set(auditId, events.slice(-AUDIT_LIMITS.maxEvents));
      },
      async appendEvent(auditId, event) {
        return this.appendAuditEvent(auditId, event);
      },
      async addCrawledPage(auditId, page) {
        const fullPage = { id: pageIdForAuditUrl(auditId, page.url), ...page };
        const client = getSupabaseAdminClient();
        if (client) {
          const { error } = await client.from("audit_pages").upsert(pageToRow(auditId, fullPage), { onConflict: "id" });
          assertNoError(error, "Add crawled page");
          return fullPage;
        }
        const pages = memory.pages.get(auditId) ?? [];
        const next = pages.filter((item) => item.id !== fullPage.id);
        next.push(fullPage);
        memory.pages.set(auditId, next);
        return fullPage;
      },
      async appendPage(auditId, page) {
        return this.addCrawledPage(auditId, page);
      },
      async addIssue(auditId, issue) {
        const fullIssue = {
          id: issue.id || randomUUID(),
          severity: issue.severity,
          category: issue.category,
          title: issue.title,
          description: issue.description,
          affectedUrl: issue.affectedUrl,
          evidence: issue.evidence,
          recommendation: issue.recommendation,
          detectedAt: issue.detectedAt || nowIso()
        };
        const client = getSupabaseAdminClient();
        if (client) {
          const countResult = await client.from("audit_issues").select("id", { count: "exact", head: true }).eq("audit_id", auditId);
          assertNoError(countResult.error, "Count audit issues");
          if ((countResult.count ?? 0) >= AUDIT_LIMITS.maxIssues) {
            return null;
          }
          const { error } = await client.from("audit_issues").insert(issueToRow(auditId, fullIssue));
          assertNoError(error, "Add audit issue");
        } else {
          const issues2 = memory.issues.get(auditId) ?? [];
          if (issues2.length >= AUDIT_LIMITS.maxIssues) {
            return null;
          }
          issues2.push(fullIssue);
          memory.issues.set(auditId, issues2);
        }
        const issues = await this.getLatestIssues(auditId, AUDIT_LIMITS.maxIssues);
        await this.updateAuditJob(auditId, {
          issuesFound: issues.length,
          criticalCount: issues.filter((item) => item.severity === "critical").length,
          highCount: issues.filter((item) => item.severity === "high").length,
          mediumCount: issues.filter((item) => item.severity === "medium").length,
          lowCount: issues.filter((item) => item.severity === "low").length
        });
        await this.appendAuditEvent(auditId, {
          type: "issue_found",
          message: fullIssue.title,
          affectedUrl: fullIssue.affectedUrl,
          category: fullIssue.category,
          severity: fullIssue.severity,
          data: {
            evidence: fullIssue.evidence,
            recommendation: fullIssue.recommendation
          }
        });
        return fullIssue;
      },
      async appendIssue(auditId, issue) {
        return this.addIssue(auditId, issue);
      },
      async getLatestEvents(auditId, limit = 50) {
        const client = getSupabaseAdminClient();
        if (client) {
          const { data, error } = await client.from("audit_events").select("*").eq("audit_id", auditId).order("created_at", { ascending: false }).limit(limit);
          assertNoError(error, "Get latest audit events");
          return (data ?? []).map(toAuditEvent).reverse();
        }
        return (memory.events.get(auditId) ?? []).slice(-limit);
      },
      async getEvents(auditId, limit = 50) {
        return this.getLatestEvents(auditId, limit);
      },
      async getLatestPages(auditId, limit = 100) {
        const client = getSupabaseAdminClient();
        if (client) {
          const { data, error } = await client.from("audit_pages").select("*").eq("audit_id", auditId).order("crawled_at", { ascending: false }).limit(limit);
          assertNoError(error, "Get latest audit pages");
          return (data ?? []).map(toAuditPage).reverse();
        }
        return (memory.pages.get(auditId) ?? []).slice(-limit);
      },
      async getPages(auditId, limit = 100) {
        return this.getLatestPages(auditId, limit);
      },
      async getLatestIssues(auditId, limit = 1e3) {
        const client = getSupabaseAdminClient();
        if (client) {
          const { data, error } = await client.from("audit_issues").select("*").eq("audit_id", auditId).order("detected_at", { ascending: false }).limit(limit);
          assertNoError(error, "Get latest audit issues");
          return (data ?? []).map(toAuditIssue).reverse();
        }
        return (memory.issues.get(auditId) ?? []).slice(-limit);
      },
      async getIssues(auditId, limit = 1e3) {
        return this.getLatestIssues(auditId, limit);
      },
      async saveFinalReport(auditId, report) {
        const client = getSupabaseAdminClient();
        if (client) {
          const { error } = await client.from("audit_reports").upsert(reportToRow(auditId, report), { onConflict: "audit_id" });
          assertNoError(error, "Save final report");
          return;
        }
        memory.reports.set(auditId, report);
      },
      async setFinalReport(auditId, report) {
        return this.saveFinalReport(auditId, report);
      },
      async getFinalReport(auditId) {
        const client = getSupabaseAdminClient();
        if (client) {
          const { data, error } = await client.from("audit_reports").select("*").eq("audit_id", auditId).maybeSingle();
          assertNoError(error, "Get final report");
          return toAuditReport(data);
        }
        return memory.reports.get(auditId) ?? null;
      },
      async getAuditLiveSnapshot(auditId) {
        return {
          audit: await this.getAuditJob(auditId),
          latestEvents: await this.getLatestEvents(auditId, 50),
          latestPages: await this.getLatestPages(auditId, 100),
          latestIssues: await this.getLatestIssues(auditId, 100),
          finalReport: await this.getFinalReport(auditId)
        };
      },
      async getLiveData(auditId) {
        return this.getAuditLiveSnapshot(auditId);
      },
      async claimQueuedAuditJob(workerId, workerRuntime = "node-worker") {
        const leaseExpiresAt = new Date(Date.now() + AUDIT_LIMITS.lockLeaseMs).toISOString();
        const timestamp = nowIso();
        const client = getSupabaseAdminClient();
        if (client) {
          const queued = await client.from("audits").select("*").eq("status", "queued").order("queue_priority", { ascending: false }).order("created_at", { ascending: true }).limit(100);
          assertNoError(queued.error, "Find queued audit job");
          let candidate = (queued.data ?? []).find((row) => isClaimableLock(row, timestamp)) ?? null;
          if (!candidate) {
            const stale = await client.from("audits").select("*").eq("status", "running").order("lease_expires_at", { ascending: true, nullsFirst: true }).order("queue_priority", { ascending: false }).order("created_at", { ascending: true }).limit(100);
            assertNoError(stale.error, "Find stale audit job");
            candidate = (stale.data ?? []).find((row) => isStaleRunningLock(row, timestamp)) ?? null;
          }
          if (!candidate) return null;
          const claimPatch = {
            status: "running",
            progress: Math.max(candidate.progress ?? 0, 1),
            current_phase: candidate.status === "running" ? "Recovering stale audit" : "Audit worker started",
            current_check: null,
            locked_by: workerId,
            locked_at: timestamp,
            lease_expires_at: leaseExpiresAt,
            worker_runtime: workerRuntime,
            started_at: candidate.started_at ?? timestamp,
            updated_at: timestamp
          };
          const attempts = [];
          if (!candidate.locked_by) attempts.push((query) => query.is("locked_by", null));
          if (!candidate.lease_expires_at) attempts.push((query) => query.is("lease_expires_at", null));
          if (candidate.lease_expires_at && String(candidate.lease_expires_at) <= timestamp) {
            attempts.push((query) => query.lte("lease_expires_at", timestamp));
          }
          for (const applyCondition of attempts) {
            const query = applyCondition(
              client.from("audits").update(claimPatch).eq("id", candidate.id).eq("status", candidate.status)
            );
            const { data, error } = await query.select("*").maybeSingle();
            assertNoError(error, "Claim audit job");
            if (data) {
              if (candidate.status === "running") {
                await this.prepareStaleAuditRetry(data.id, workerId);
                return this.getAuditJob(data.id);
              }
              return toAuditDocument(data);
            }
          }
          return null;
        }
        const next = Array.from(memory.audits.values()).filter((audit) => {
          if (audit.status === "queued") return !audit.lockedBy || !audit.leaseExpiresAt || audit.leaseExpiresAt <= timestamp;
          return audit.status === "running" && (!audit.leaseExpiresAt || audit.leaseExpiresAt <= timestamp);
        }).sort((a, b) => b.queuePriority - a.queuePriority || a.createdAt.localeCompare(b.createdAt))[0];
        if (!next) return null;
        const claimed = {
          ...next,
          status: "running",
          progress: Math.max(next.progress, 1),
          currentPhase: "Audit worker started",
          lockedBy: workerId,
          lockedAt: timestamp,
          leaseExpiresAt,
          workerRuntime,
          startedAt: next.startedAt ?? timestamp,
          updatedAt: timestamp
        };
        memory.audits.set(next.id, claimed);
        return claimed;
      },
      async claimNextQueuedAudit(workerId, workerRuntime) {
        return this.claimQueuedAuditJob(workerId, workerRuntime);
      },
      async refreshAuditLease(auditId, workerId) {
        const timestamp = nowIso();
        const leaseExpiresAt = new Date(Date.now() + AUDIT_LIMITS.lockLeaseMs).toISOString();
        const client = getSupabaseAdminClient();
        if (client) {
          const { data, error } = await client.from("audits").update({
            locked_by: workerId,
            lease_expires_at: leaseExpiresAt,
            updated_at: timestamp
          }).eq("id", auditId).eq("status", "running").eq("locked_by", workerId).select("id").maybeSingle();
          assertNoError(error, "Refresh audit lease");
          return Boolean(data);
        }
        const current = memory.audits.get(auditId);
        if (!current || current.status !== "running" || current.lockedBy !== workerId) return false;
        memory.audits.set(auditId, {
          ...current,
          leaseExpiresAt,
          updatedAt: timestamp
        });
        return true;
      },
      async releaseAuditLease(auditId, workerId) {
        const timestamp = nowIso();
        const client = getSupabaseAdminClient();
        if (client) {
          const { error } = await client.from("audits").update({
            locked_by: null,
            locked_at: null,
            lease_expires_at: null,
            updated_at: timestamp
          }).eq("id", auditId).eq("locked_by", workerId);
          assertNoError(error, "Release audit lease");
          return;
        }
        const current = memory.audits.get(auditId);
        if (current?.lockedBy === workerId) {
          memory.audits.set(auditId, {
            ...current,
            lockedBy: null,
            lockedAt: null,
            leaseExpiresAt: null,
            updatedAt: timestamp
          });
        }
      },
      async expireAuditLease(auditId, workerId) {
        const timestamp = nowIso();
        const client = getSupabaseAdminClient();
        if (client) {
          const { error } = await client.from("audits").update({
            locked_by: null,
            locked_at: null,
            lease_expires_at: timestamp,
            current_phase: "Worker stopped; waiting for another worker",
            current_check: null,
            updated_at: timestamp
          }).eq("id", auditId).eq("locked_by", workerId);
          assertNoError(error, "Expire audit lease");
          return;
        }
        const current = memory.audits.get(auditId);
        if (current?.lockedBy === workerId) {
          memory.audits.set(auditId, {
            ...current,
            lockedBy: null,
            lockedAt: null,
            leaseExpiresAt: timestamp,
            currentPhase: "Worker stopped; waiting for another worker",
            currentCheck: null,
            updatedAt: timestamp
          });
        }
      },
      async prepareStaleAuditRetry(auditId, workerId) {
        const client = getSupabaseAdminClient();
        if (client) {
          for (const table of ["audit_pages", "audit_issues", "audit_reports"]) {
            const { error } = await client.from(table).delete().eq("audit_id", auditId);
            assertNoError(error, `Clear stale ${table}`);
          }
        } else {
          memory.pages.set(auditId, []);
          memory.issues.set(auditId, []);
          memory.reports.delete(auditId);
        }
        await this.appendAuditEvent(auditId, {
          type: "audit_recovered",
          message: `Audit recovered by ${workerId} after a stale worker lease.`,
          phase: "Recovering stale audit"
        });
        await this.updateAuditJob(auditId, {
          status: "running",
          progress: 1,
          currentPhase: "Recovering stale audit",
          currentUrl: null,
          currentCheck: null,
          pagesDiscovered: 0,
          pagesCrawled: 0,
          checksTotal: 0,
          checksCompleted: 0,
          issuesFound: 0,
          criticalCount: 0,
          highCount: 0,
          mediumCount: 0,
          lowCount: 0,
          finalUrl: null,
          error: null
        });
      },
      async releaseAuditLock(id) {
        await this.updateAuditJob(id, {
          lockedBy: null,
          lockedAt: null,
          leaseExpiresAt: null
        });
      },
      async cleanupOldAudits(limit = 25) {
        const client = getSupabaseAdminClient();
        const current = nowIso();
        if (!client) {
          for (const audit of memory.audits.values()) {
            if (audit.expiresAt < current) {
              memory.events.delete(audit.id);
              memory.pages.delete(audit.id);
              memory.issues.delete(audit.id);
              memory.reports.delete(audit.id);
              memory.audits.delete(audit.id);
            }
          }
          return;
        }
        const { error } = await client.from("audits").delete().lt("expires_at", current).limit(limit);
        assertNoError(error, "Clean up old audits");
      },
      async clearExpiredAuditData() {
        return this.cleanupOldAudits();
      }
    };
  }
});

// src/lib/billing/entitlements.ts
import { randomUUID as randomUUID2 } from "node:crypto";
function nextDailyResetMs() {
  const date = /* @__PURE__ */ new Date();
  date.setUTCHours(24, 0, 0, 0);
  return date.getTime();
}
function nextMonthlyResetMs() {
  const date = /* @__PURE__ */ new Date();
  date.setUTCMonth(date.getUTCMonth() + 1, 1);
  date.setUTCHours(0, 0, 0, 0);
  return date.getTime();
}
function normalizeRole(value) {
  if (value === "admin") return "admin";
  if (value === "support" || value === "staff") return "support";
  return "user";
}
function normalizePlan(value) {
  if (value === "paid" || value === "agency" || value === "admin") return value;
  return "free";
}
function normalizeSubscriptionStatus(value) {
  if (value === "trialing" || value === "active" || value === "past_due" || value === "cancelled") return value;
  return "inactive";
}
function getAdminEmailSet() {
  return new Set(
    String(process.env.ADMIN_EMAILS || "").split(",").map((email) => email.trim().toLowerCase()).filter(Boolean)
  );
}
function isBootstrapAdminEmail(email) {
  if (!email) return false;
  return getAdminEmailSet().has(email.trim().toLowerCase());
}
function rowToPlanLimits(row) {
  const fallback = DEFAULT_PLAN_LIMITS[normalizePlan(row?.plan)];
  return {
    plan: fallback.plan,
    label: row?.label ?? fallback.label,
    dailyAudits: row?.daily_audits ?? fallback.dailyAudits,
    monthlyAudits: row?.monthly_audits ?? fallback.monthlyAudits,
    maxPagesQuick: row?.max_pages_quick ?? fallback.maxPagesQuick,
    maxPagesStandard: row?.max_pages_standard ?? fallback.maxPagesStandard,
    maxPagesDeep: row?.max_pages_deep ?? fallback.maxPagesDeep,
    allowedModes: row?.allowed_modes ?? fallback.allowedModes,
    auditTimeoutSeconds: row?.audit_timeout_seconds ?? fallback.auditTimeoutSeconds,
    concurrency: row?.concurrency ?? fallback.concurrency,
    maxEventsPerAudit: row?.max_events_per_audit ?? fallback.maxEventsPerAudit,
    maxIssuesPerAudit: row?.max_issues_per_audit ?? fallback.maxIssuesPerAudit,
    priority: row?.priority ?? fallback.priority,
    exportsEnabled: row?.exports_enabled ?? fallback.exportsEnabled,
    pdfEnabled: row?.pdf_enabled ?? fallback.pdfEnabled,
    whiteLabelEnabled: row?.white_label_enabled ?? fallback.whiteLabelEnabled,
    embedEnabled: row?.embed_enabled ?? fallback.embedEnabled,
    apiEnabled: row?.api_enabled ?? fallback.apiEnabled,
    scheduledAuditsEnabled: row?.scheduled_audits_enabled ?? fallback.scheduledAuditsEnabled
  };
}
function rowToProfile(row) {
  return {
    id: row.id,
    email: row.email ?? null,
    fullName: row.full_name ?? row.display_name ?? null,
    role: normalizeRole(row.role),
    plan: normalizePlan(row.plan),
    subscriptionStatus: normalizeSubscriptionStatus(row.subscription_status),
    auditQuotaUsedDaily: Number(row.audit_quota_used_daily ?? 0),
    auditQuotaUsedMonthly: Number(row.audit_quota_used_monthly ?? 0)
  };
}
async function getAuthenticatedUserFromRequest(req) {
  const header = String(req.headers?.authorization || req.headers?.Authorization || "");
  const token = header.startsWith("Bearer ") ? header.slice("Bearer ".length).trim() : "";
  if (!token) return null;
  const client = getSupabaseAdminClient();
  if (!client) return null;
  const { data, error } = await client.auth.getUser(token);
  if (error || !data.user) return null;
  return data.user;
}
async function ensureUserProfileFromAuthUser(user) {
  const client = requireSupabaseAdminClient();
  const email = user.email ?? null;
  const isAdminEmail = isBootstrapAdminEmail(email);
  const timestamp = (/* @__PURE__ */ new Date()).toISOString();
  const metadata = user.user_metadata || {};
  const fullName = metadata.full_name || metadata.display_name || (email ? email.split("@")[0] : "User");
  const { data: existing, error: readError } = await client.from("user_profiles").select("*").eq("id", user.id).maybeSingle();
  if (readError) throw readError;
  const nextRole = isAdminEmail ? "admin" : normalizeRole(existing?.role);
  const nextPlan = isAdminEmail ? "admin" : normalizePlan(existing?.plan);
  const nextSubscriptionStatus = nextPlan === "free" ? normalizeSubscriptionStatus(existing?.subscription_status) : "active";
  const { data, error } = await client.from("user_profiles").upsert(
    {
      id: user.id,
      email,
      full_name: existing?.full_name ?? fullName,
      role: nextRole,
      plan: nextPlan,
      subscription_status: nextSubscriptionStatus,
      quota_reset_daily_at: existing?.quota_reset_daily_at ?? new Date(nextDailyResetMs()).toISOString(),
      quota_reset_monthly_at: existing?.quota_reset_monthly_at ?? new Date(nextMonthlyResetMs()).toISOString(),
      updated_at: timestamp
    },
    { onConflict: "id" }
  ).select("*").single();
  if (error) throw error;
  return rowToProfile(data);
}
async function getPlanLimits(plan) {
  const fallback = DEFAULT_PLAN_LIMITS[normalizePlan(plan)];
  const client = getSupabaseAdminClient();
  if (!client) return fallback;
  const { data, error } = await client.from("plan_limits").select("*").eq("plan", fallback.plan).maybeSingle();
  if (error || !data) return fallback;
  return rowToPlanLimits(data);
}
async function getUserEntitlements(userId) {
  const client = requireSupabaseAdminClient();
  await resetQuotaIfNeeded(userId);
  const { data, error } = await client.from("user_profiles").select("*").eq("id", userId).maybeSingle();
  if (error) throw error;
  if (!data) throw new EntitlementError("User profile not found.", { status: 401 });
  const profile = rowToProfile(data);
  return { profile, limits: await getPlanLimits(profile.plan) };
}
function resolveEffectiveAuditMode(userPlan, requestedMode, options = {}) {
  const plan = normalizePlan(userPlan);
  if (plan === "free" && requestedMode !== "quick") {
    throw new EntitlementError("Standard and Deep audits require a paid plan.", { upgradeRequired: true });
  }
  if (plan === "paid" && requestedMode === "deep") {
    throw new EntitlementError("Deep Audit requires an agency plan.", { upgradeRequired: true });
  }
  if ((plan === "agency" || plan === "admin") && requestedMode === "deep" && !options.deepAuditEnabled) {
    throw new EntitlementError("Deep Audit requires a dedicated always-on worker.", { upgradeRequired: plan !== "admin" });
  }
  return requestedMode;
}
function pageLimitForMode(limits, mode) {
  if (mode === "deep") return limits.maxPagesDeep;
  if (mode === "standard") return limits.maxPagesStandard;
  return limits.maxPagesQuick;
}
async function getActiveAuditCount(userId) {
  const client = requireSupabaseAdminClient();
  const { count, error } = await client.from("audits").select("id", { count: "exact", head: true }).eq("user_id", userId).in("status", ["queued", "running"]);
  if (error) throw error;
  return count ?? 0;
}
function getGuestUsage(guestKey) {
  const now = Date.now();
  const existing = guestUsage.get(guestKey) ?? {
    daily: 0,
    monthly: 0,
    dailyResetAt: nextDailyResetMs(),
    monthlyResetAt: nextMonthlyResetMs()
  };
  if (existing.dailyResetAt <= now) {
    existing.daily = 0;
    existing.dailyResetAt = nextDailyResetMs();
  }
  if (existing.monthlyResetAt <= now) {
    existing.monthly = 0;
    existing.monthlyResetAt = nextMonthlyResetMs();
  }
  guestUsage.set(guestKey, existing);
  return existing;
}
async function canStartAudit(userId, requestedMode, options = {}) {
  const effectiveMode = resolveEffectiveAuditMode(userId ? (await getUserEntitlements(userId)).profile.plan : "free", requestedMode, options);
  if (!userId) {
    const limits2 = DEFAULT_PLAN_LIMITS.free;
    const usage = getGuestUsage(options.guestKey || "guest:unknown");
    if (usage.daily >= limits2.dailyAudits || usage.monthly >= limits2.monthlyAudits) {
      throw new EntitlementError("You have reached your free audit limit. Upgrade for more audits.", { status: 429, upgradeRequired: true });
    }
    return {
      userId: null,
      plan: "free",
      role: "user",
      subscriptionStatus: "inactive",
      requestedMode,
      effectiveMode,
      processingTier: "free",
      pageLimit: limits2.maxPagesQuick,
      queuePriority: limits2.priority,
      quotaRemaining: {
        daily: Math.max(0, limits2.dailyAudits - usage.daily - 1),
        monthly: Math.max(0, limits2.monthlyAudits - usage.monthly - 1)
      },
      limits: limits2
    };
  }
  const { profile, limits } = await getUserEntitlements(userId);
  const finalMode = resolveEffectiveAuditMode(profile.plan, requestedMode, options);
  if (!limits.allowedModes.includes(finalMode)) {
    throw new EntitlementError("This audit mode is not enabled for your plan.", { upgradeRequired: true });
  }
  if (profile.plan === "free" && await getActiveAuditCount(userId) > 0) {
    throw new EntitlementError("You already have an audit in progress. Please wait for it to finish.", { status: 429 });
  }
  if (profile.plan !== "admin") {
    if (profile.auditQuotaUsedDaily >= limits.dailyAudits || profile.auditQuotaUsedMonthly >= limits.monthlyAudits) {
      throw new EntitlementError("You have reached your free audit limit. Upgrade for more audits.", {
        status: 429,
        upgradeRequired: profile.plan === "free"
      });
    }
  }
  return {
    userId,
    plan: profile.plan,
    role: profile.role,
    subscriptionStatus: profile.subscriptionStatus,
    requestedMode,
    effectiveMode: finalMode,
    processingTier: profile.plan,
    pageLimit: pageLimitForMode(limits, finalMode),
    queuePriority: limits.priority,
    quotaRemaining: {
      daily: Math.max(0, limits.dailyAudits - profile.auditQuotaUsedDaily - 1),
      monthly: Math.max(0, limits.monthlyAudits - profile.auditQuotaUsedMonthly - 1)
    },
    limits
  };
}
async function consumeAuditQuota(userId, auditId, mode, options = {}) {
  if (!userId) {
    const usage = getGuestUsage(options.guestKey || "guest:unknown");
    usage.daily += 1;
    usage.monthly += 1;
    return;
  }
  const client = requireSupabaseAdminClient();
  const { data: profile, error: readError } = await client.from("user_profiles").select("audit_quota_used_daily,audit_quota_used_monthly,plan").eq("id", userId).maybeSingle();
  if (readError) throw readError;
  const plan = normalizePlan(options.plan || profile?.plan);
  const { error: updateError } = await client.from("user_profiles").update({
    audit_quota_used_daily: Number(profile?.audit_quota_used_daily ?? 0) + 1,
    audit_quota_used_monthly: Number(profile?.audit_quota_used_monthly ?? 0) + 1,
    updated_at: (/* @__PURE__ */ new Date()).toISOString()
  }).eq("id", userId);
  if (updateError) throw updateError;
  const { error: insertError } = await client.from("audit_usage_events").insert({
    id: randomUUID2(),
    user_id: userId,
    audit_id: auditId,
    plan,
    mode,
    pages_limit: options.pagesLimit ?? null
  });
  if (insertError) throw insertError;
}
async function resetQuotaIfNeeded(userId) {
  const client = requireSupabaseAdminClient();
  const { data, error } = await client.from("user_profiles").select("quota_reset_daily_at,quota_reset_monthly_at").eq("id", userId).maybeSingle();
  if (error || !data) {
    if (error) throw error;
    return;
  }
  const now = Date.now();
  const patch = {};
  if (!data.quota_reset_daily_at || new Date(data.quota_reset_daily_at).getTime() <= now) {
    patch.audit_quota_used_daily = 0;
    patch.quota_reset_daily_at = new Date(nextDailyResetMs()).toISOString();
  }
  if (!data.quota_reset_monthly_at || new Date(data.quota_reset_monthly_at).getTime() <= now) {
    patch.audit_quota_used_monthly = 0;
    patch.quota_reset_monthly_at = new Date(nextMonthlyResetMs()).toISOString();
  }
  if (Object.keys(patch).length) {
    patch.updated_at = (/* @__PURE__ */ new Date()).toISOString();
    const { error: updateError } = await client.from("user_profiles").update(patch).eq("id", userId);
    if (updateError) throw updateError;
  }
}
var EntitlementError, DEFAULT_PLAN_LIMITS, guestUsage;
var init_entitlements = __esm({
  "src/lib/billing/entitlements.ts"() {
    init_server();
    EntitlementError = class extends Error {
      constructor(message, options = {}) {
        super(message);
        this.name = "EntitlementError";
        this.status = options.status ?? 403;
        this.upgradeRequired = options.upgradeRequired ?? false;
      }
    };
    DEFAULT_PLAN_LIMITS = {
      free: {
        plan: "free",
        label: "Free",
        dailyAudits: 3,
        monthlyAudits: 30,
        maxPagesQuick: 5,
        maxPagesStandard: 0,
        maxPagesDeep: 0,
        allowedModes: ["quick"],
        auditTimeoutSeconds: 5,
        concurrency: 1,
        maxEventsPerAudit: 100,
        maxIssuesPerAudit: 150,
        priority: 10,
        exportsEnabled: true,
        pdfEnabled: false,
        whiteLabelEnabled: false,
        embedEnabled: false,
        apiEnabled: false,
        scheduledAuditsEnabled: false
      },
      paid: {
        plan: "paid",
        label: "Paid",
        dailyAudits: 25,
        monthlyAudits: 500,
        maxPagesQuick: 10,
        maxPagesStandard: 25,
        maxPagesDeep: 0,
        allowedModes: ["quick", "standard"],
        auditTimeoutSeconds: 8,
        concurrency: 2,
        maxEventsPerAudit: 300,
        maxIssuesPerAudit: 1e3,
        priority: 50,
        exportsEnabled: true,
        pdfEnabled: true,
        whiteLabelEnabled: true,
        embedEnabled: false,
        apiEnabled: false,
        scheduledAuditsEnabled: false
      },
      agency: {
        plan: "agency",
        label: "Agency",
        dailyAudits: 100,
        monthlyAudits: 3e3,
        maxPagesQuick: 10,
        maxPagesStandard: 25,
        maxPagesDeep: 50,
        allowedModes: ["quick", "standard", "deep"],
        auditTimeoutSeconds: 10,
        concurrency: 3,
        maxEventsPerAudit: 500,
        maxIssuesPerAudit: 3e3,
        priority: 100,
        exportsEnabled: true,
        pdfEnabled: true,
        whiteLabelEnabled: true,
        embedEnabled: true,
        apiEnabled: true,
        scheduledAuditsEnabled: true
      },
      admin: {
        plan: "admin",
        label: "Admin",
        dailyAudits: 1e3,
        monthlyAudits: 1e5,
        maxPagesQuick: 10,
        maxPagesStandard: 25,
        maxPagesDeep: 75,
        allowedModes: ["quick", "standard", "deep"],
        auditTimeoutSeconds: 10,
        concurrency: 3,
        maxEventsPerAudit: 1e3,
        maxIssuesPerAudit: 5e3,
        priority: 999,
        exportsEnabled: true,
        pdfEnabled: true,
        whiteLabelEnabled: true,
        embedEnabled: true,
        apiEnabled: true,
        scheduledAuditsEnabled: true
      }
    };
    guestUsage = /* @__PURE__ */ new Map();
  }
});

// src/api/index.ts
var index_exports = {};
__export(index_exports, {
  apiRouter: () => apiRouter
});
import { createHash as createHash2 } from "node:crypto";
import { Router } from "express";
function asyncJsonRoute(handler2) {
  return async (req, res, next) => {
    try {
      await handler2(req, res, next);
    } catch (error) {
      console.error(error);
      if (!res.headersSent) {
        res.status(500).json({
          success: false,
          error: error instanceof Error ? error.message : "Internal server error"
        });
      }
    }
  };
}
function firstHeaderValue(value) {
  return Array.isArray(value) ? String(value[0] || "") : String(value || "");
}
function hashGuestValue(value) {
  return createHash2("sha256").update(value).digest("hex");
}
function getCookieValue(req, name) {
  if (req.cookies?.[name]) return String(req.cookies[name]);
  const cookieHeader = firstHeaderValue(req.headers?.cookie);
  const match = cookieHeader.split(";").map((part) => part.trim()).find((part) => part.startsWith(`${name}=`));
  return match ? decodeURIComponent(match.slice(name.length + 1)) : "";
}
function guestIdentityForRequest(req) {
  const explicitGuestId = firstHeaderValue(req.headers?.["x-seointel-guest-id"]) || getCookieValue(req, "seointel_guest_id");
  if (explicitGuestId) {
    const guestKeyHash2 = hashGuestValue(`guest-session:${explicitGuestId.slice(0, 128)}`);
    return { guestKey: `guest:${guestKeyHash2}`, guestKeyHash: guestKeyHash2 };
  }
  const forwarded = String(req.headers?.["x-forwarded-for"] || "").split(",")[0].trim();
  const userAgent = firstHeaderValue(req.headers?.["user-agent"]).slice(0, 256);
  const fallback = `${forwarded || req.ip || req.socket?.remoteAddress || "unknown"}|${userAgent}`;
  const guestKeyHash = hashGuestValue(`guest-network:${fallback}`);
  return { guestKey: `guest:${guestKeyHash}`, guestKeyHash };
}
function isDeepAuditEnabled() {
  return process.env.DEEP_AUDIT_ENABLED === "true";
}
async function getRequester(req) {
  const authUser = await getAuthenticatedUserFromRequest(req);
  if (!authUser) return { userId: null, profile: null };
  const profile = await ensureUserProfileFromAuthUser(authUser);
  return { userId: authUser.id, profile };
}
function sendEntitlementError(res, error) {
  if (error instanceof EntitlementError) {
    return res.status(error.status).json({
      success: false,
      error: error.message,
      upgradeRequired: error.upgradeRequired
    });
  }
  throw error;
}
function auditStartResponseData(audit, extras = {}) {
  return {
    auditId: audit.id,
    status: audit.status,
    submittedInput: audit.submittedInput,
    normalizedUrl: audit.normalizedUrl,
    hostname: audit.hostname,
    requestedMode: audit.requestedMode,
    effectiveMode: audit.effectiveMode,
    plan: audit.plan,
    pageLimit: audit.pageLimit,
    queuePriority: audit.queuePriority,
    ...extras
  };
}
async function startQueuedAudit(req, res, defaultMode = "quick") {
  const { url, mode = defaultMode, projectId = null } = req.body || {};
  const normalized = normalizeUserUrl(String(url || ""));
  if (!normalized.isValid) {
    return res.status(400).json({ success: false, error: normalized.error || "Invalid URL" });
  }
  const requestedMode = getAuditModeConfig(mode).mode;
  const { userId } = await getRequester(req);
  const guestIdentity = guestIdentityForRequest(req);
  const ownerLookup = userId ? { userId, guestKeyHash: null } : { userId: null, guestKeyHash: guestIdentity.guestKeyHash };
  const createdAfterIso = new Date(Date.now() - DUPLICATE_AUDIT_WINDOW_MS).toISOString();
  const duplicateAudit = await auditRepository.findActiveDuplicateAudit({
    ...ownerLookup,
    normalizedUrl: normalized.normalizedUrl,
    createdAfterIso
  });
  if (duplicateAudit) {
    return res.json({
      success: true,
      data: auditStartResponseData(duplicateAudit, { reusedExistingAudit: true })
    });
  }
  if (!userId) {
    const activeGuestAudit = await auditRepository.findActiveAuditForOwner(ownerLookup);
    if (activeGuestAudit) {
      return res.json({
        success: true,
        message: "You already have an audit in progress.",
        data: auditStartResponseData(activeGuestAudit, { reusedExistingAudit: true })
      });
    }
  }
  let decision;
  try {
    decision = await canStartAudit(userId, requestedMode, {
      guestKey: guestIdentity.guestKey,
      deepAuditEnabled: isDeepAuditEnabled()
    });
  } catch (error) {
    if (error instanceof EntitlementError && /already have an audit in progress/i.test(error.message)) {
      const activeAudit = await auditRepository.findActiveAuditForOwner(ownerLookup);
      if (activeAudit) {
        return res.json({
          success: true,
          message: "You already have an audit in progress.",
          data: auditStartResponseData(activeAudit, { reusedExistingAudit: true })
        });
      }
    }
    return sendEntitlementError(res, error);
  }
  const audit = await auditRepository.createAuditJob({
    submittedInput: String(url || "").trim(),
    normalizedUrl: normalized.normalizedUrl,
    hostname: normalized.hostname,
    mode: decision.effectiveMode,
    requestedMode: decision.requestedMode,
    effectiveMode: decision.effectiveMode,
    plan: decision.plan,
    processingTier: decision.processingTier,
    pageLimit: decision.pageLimit,
    queuePriority: decision.queuePriority,
    userId: decision.userId,
    guestKeyHash: decision.userId ? null : guestIdentity.guestKeyHash,
    projectId
  });
  await consumeAuditQuota(decision.userId, audit.id, decision.effectiveMode, {
    plan: decision.plan,
    pagesLimit: decision.pageLimit,
    guestKey: guestIdentity.guestKey
  });
  await auditRepository.updateAudit(audit.id, { quotaCounted: true });
  console.info(`Audit start using Supabase project: ${getSupabaseProjectHostname() || "not configured"}`);
  res.json({
    success: true,
    data: {
      ...auditStartResponseData(audit),
      quotaRemaining: decision.quotaRemaining,
      reusedExistingAudit: false
    }
  });
}
var DUPLICATE_AUDIT_WINDOW_MS, apiRouter;
var init_index = __esm({
  "src/api/index.ts"() {
    init_url_utils();
    init_generator();
    init_clustering();
    init_content_brief();
    init_audit_store();
    init_audit_repository();
    init_server();
    init_resource_types();
    init_entitlements();
    DUPLICATE_AUDIT_WINDOW_MS = 10 * 60 * 1e3;
    apiRouter = Router();
    apiRouter.get("/me/profile", asyncJsonRoute(async (req, res) => {
      const authUser = await getAuthenticatedUserFromRequest(req);
      if (!authUser) {
        return res.status(401).json({ success: false, error: "Not authenticated" });
      }
      const profile = await ensureUserProfileFromAuthUser(authUser);
      const limits = await getPlanLimits(profile.plan);
      res.json({ success: true, data: { profile, limits } });
    }));
    apiRouter.post("/audit/start", asyncJsonRoute(async (req, res) => {
      try {
        return startQueuedAudit(req, res, "quick");
      } catch (error) {
        res.status(500).json({ success: false, error: error.message || "Internal Server Error" });
      }
    }));
    apiRouter.get("/audit/events/:id", asyncJsonRoute((req, res) => {
      const auditId = req.params.id;
      const audit = typeof auditStore.getAudit === "function" ? auditStore.getAudit(auditId) : auditStore.getJob(auditId);
      if (!audit) {
        return res.status(404).json({ success: false, error: "Audit not found" });
      }
      res.setHeader("Content-Type", "text/event-stream");
      res.setHeader("Cache-Control", "no-cache, no-transform");
      res.setHeader("Connection", "keep-alive");
      res.flushHeaders();
      const sendEvent = (eventType, data) => {
        res.write(`event: ${eventType}
`);
        res.write(`data: ${JSON.stringify(data)}

`);
      };
      const history = typeof auditStore.getAuditEvents === "function" ? auditStore.getAuditEvents(auditId) : [];
      for (const ev of history) {
        sendEvent("audit-event", ev);
      }
      const onEvent = (ev) => {
        sendEvent("audit-event", ev);
        if (ev.type === "audit_completed") {
          sendEvent("audit-complete", { auditId, resultAvailable: true });
        } else if (ev.type === "audit_failed") {
          sendEvent("audit-error", { auditId, error: ev.message });
        }
      };
      if (typeof auditStore.subscribeToAudit === "function") {
        auditStore.subscribeToAudit(auditId, onEvent);
      }
      const heartbeat = setInterval(() => {
        res.write(": heartbeat\n\n");
      }, 15e3);
      req.on("close", () => {
        clearInterval(heartbeat);
        if (typeof auditStore.unsubscribeFromAudit === "function") {
          auditStore.unsubscribeFromAudit(auditId, onEvent);
        }
      });
    }));
    apiRouter.get("/audit/status/:id", asyncJsonRoute(async (req, res) => {
      try {
        const liveData = await auditRepository.getLiveData(req.params.id);
        if (!liveData.audit) return res.status(404).json({ success: false, error: "Audit not found" });
        res.json({ success: true, data: liveData });
      } catch (error) {
        res.status(500).json({ success: false, error: error.message || "Internal Server Error" });
      }
    }));
    apiRouter.post("/audit/cancel/:id", asyncJsonRoute(async (req, res) => {
      const audit = await auditRepository.getAudit(req.params.id);
      if (!audit) return res.status(404).json({ success: false, error: "Audit not found" });
      await auditRepository.cancelAudit(req.params.id);
      res.json({ success: true, data: { auditId: req.params.id, status: "cancelled" } });
    }));
    apiRouter.get("/audit/result/:id", asyncJsonRoute(async (req, res) => {
      try {
        const liveData = await auditRepository.getLiveData(req.params.id);
        if (!liveData.audit) return res.status(404).json({ success: false, error: "Audit not found" });
        res.json({ success: true, data: liveData });
      } catch (error) {
        res.status(500).json({ success: false, error: error.message || "Internal Server Error" });
      }
    }));
    apiRouter.get("/audit/export/:id/:format", asyncJsonRoute(async (req, res) => {
      const { id, format } = req.params;
      const liveData = await auditRepository.getLiveData(id);
      if (!liveData.audit) return res.status(404).json({ success: false, error: "Audit not found" });
      if (format === "json") {
        return res.json({ success: true, data: liveData.finalReport || liveData });
      }
      if (format === "issues.csv") {
        const header = "severity,category,title,affectedUrl,evidence,recommendation\n";
        const rows = liveData.latestIssues.map((issue) => [issue.severity, issue.category, issue.title, issue.affectedUrl, issue.evidence, issue.recommendation].map((value) => `"${String(value || "").replace(/"/g, '""')}"`).join(",")).join("\n");
        res.setHeader("Content-Type", "text/csv; charset=utf-8");
        return res.send(header + rows);
      }
      if (format === "pages.csv") {
        const header = "statusCode,url,responseTimeMs,pageSizeBytes,title,wordCount,crawlDepth,issueCount\n";
        const rows = liveData.latestPages.map((page) => [page.statusCode, page.url, page.responseTimeMs, page.pageSizeBytes, page.title, page.wordCount, page.crawlDepth, page.issueCount].map((value) => `"${String(value || "").replace(/"/g, '""')}"`).join(",")).join("\n");
        res.setHeader("Content-Type", "text/csv; charset=utf-8");
        return res.send(header + rows);
      }
      return res.status(400).json({ success: false, error: "Unsupported export format" });
    }));
    apiRouter.post("/audit/rerun/:id", asyncJsonRoute((req, res) => {
      try {
        return res.status(409).json({ success: false, error: "Rerun is disabled for worker-backed audits. Start a new audit instead." });
      } catch (error) {
        res.status(500).json({ success: false, error: error.message || "Internal Server Error" });
      }
    }));
    apiRouter.post("/keyword/research", asyncJsonRoute((req, res) => {
      try {
        const { seed } = req.body;
        if (!seed) return res.status(400).json({ success: false, error: "Seed keyword is required" });
        const keywords = generateKeywords(seed);
        res.json({ success: true, data: { keywords } });
      } catch (error) {
        res.status(500).json({ success: false, error: error.message || "Internal Server Error" });
      }
    }));
    apiRouter.post("/website/analyze", asyncJsonRoute(async (req, res) => {
      try {
        return startQueuedAudit(req, res, "standard");
      } catch (e) {
        res.status(500).json({ success: false, error: e.message || "Internal Server Error" });
      }
    }));
    apiRouter.post("/clusters", asyncJsonRoute((req, res) => {
      try {
        const { keywords } = req.body;
        if (!keywords || !Array.isArray(keywords)) return res.status(400).json({ success: false, error: "Keywords array is required" });
        const clusters = clusterKeywords(keywords);
        res.json({ success: true, data: { clusters } });
      } catch (error) {
        res.status(500).json({ success: false, error: error.message || "Internal Server Error" });
      }
    }));
    apiRouter.post("/content-brief", asyncJsonRoute((req, res) => {
      try {
        const { cluster } = req.body;
        if (!cluster) return res.status(400).json({ success: false, error: "Cluster object is required" });
        const brief = buildContentBrief(cluster);
        res.json({ success: true, data: { brief } });
      } catch (error) {
        res.status(500).json({ success: false, error: error.message || "Internal Server Error" });
      }
    }));
    apiRouter.post("/competitor-gap", asyncJsonRoute(async (req, res) => {
      return res.status(501).json({
        success: false,
        error: "Competitor Gap is temporarily disabled while worker-backed analysis is being enabled."
      });
    }));
  }
});

// src/api/vercel-handler.ts
import express2 from "express";

// src/lib/api/http-hardening.ts
import express from "express";
var stores = /* @__PURE__ */ new Map();
var DEFAULT_RATE_LIMIT_MAX_KEYS = 1e4;
function apiSecurityHeaders(_req, res, next) {
  res.setHeader("X-Content-Type-Options", "nosniff");
  res.setHeader("X-Frame-Options", "DENY");
  res.setHeader("Referrer-Policy", "strict-origin-when-cross-origin");
  res.setHeader("Cross-Origin-Opener-Policy", "same-origin");
  res.setHeader("Permissions-Policy", "camera=(), microphone=(), geolocation=(), payment=()");
  res.setHeader("Content-Security-Policy", "frame-ancestors 'none'; base-uri 'self'; object-src 'none'");
  next();
}
function jsonBodyParser() {
  return express.json({
    limit: process.env.API_JSON_BODY_LIMIT || "64kb",
    strict: true
  });
}
function jsonParseErrorHandler(error, _req, res, next) {
  if (error?.type === "entity.too.large") {
    return res.status(413).json({
      success: false,
      error: "Request body is too large"
    });
  }
  if (error instanceof SyntaxError && "body" in error) {
    return res.status(400).json({
      success: false,
      error: "Invalid JSON request body"
    });
  }
  next(error);
}
function apiErrorHandler(error, req, res, _next) {
  console.error("[api] unhandled route error", {
    message: error?.message,
    stack: error?.stack,
    method: req.method,
    url: req.originalUrl || req.url
  });
  if (!res.headersSent) {
    res.status(500).json({
      success: false,
      error: "Internal server error"
    });
  }
}
function clientIp(req) {
  const forwardedFor = req.headers["x-forwarded-for"];
  const forwardedValue = Array.isArray(forwardedFor) ? forwardedFor[0] : forwardedFor;
  return req.ip || req.socket.remoteAddress || forwardedValue?.split(",")[0]?.trim() || "unknown";
}
function storeFor(namespace) {
  let store = stores.get(namespace);
  if (!store) {
    store = /* @__PURE__ */ new Map();
    stores.set(namespace, store);
  }
  return store;
}
function pruneStore(store, now, maxKeys) {
  if (store.size <= maxKeys) {
    return;
  }
  for (const [key, entry] of store) {
    if (entry.resetAt <= now) {
      store.delete(key);
    }
  }
  while (store.size > maxKeys) {
    const oldestKey = store.keys().next().value;
    if (!oldestKey) {
      break;
    }
    store.delete(oldestKey);
  }
}
function createRateLimiter(options) {
  return (req, res, next) => {
    const now = Date.now();
    const store = storeFor(options.namespace);
    pruneStore(store, now, options.maxKeys || DEFAULT_RATE_LIMIT_MAX_KEYS);
    const key = `${clientIp(req)}:${req.method}:${req.path}`;
    const current = store.get(key);
    if (!current || current.resetAt <= now) {
      store.set(key, { count: 1, resetAt: now + options.windowMs });
      return next();
    }
    current.count += 1;
    if (current.count <= options.maxRequests) {
      return next();
    }
    const retryAfterSeconds = Math.max(1, Math.ceil((current.resetAt - now) / 1e3));
    res.setHeader("Retry-After", String(retryAfterSeconds));
    return res.status(429).json({
      success: false,
      error: "Too many requests. Please retry shortly."
    });
  };
}

// src/api/vercel-handler.ts
var cachedApp = null;
function rewriteVercelPath(req) {
  const requestUrl = new URL(req.url || "/", "http://localhost");
  const path = requestUrl.searchParams.get("path");
  if (!path) return;
  requestUrl.searchParams.delete("path");
  const query = requestUrl.searchParams.toString();
  req.url = `/api/${path}${query ? `?${query}` : ""}`;
}
async function getApp() {
  if (cachedApp) return cachedApp;
  const { apiRouter: apiRouter2 } = await Promise.resolve().then(() => (init_index(), index_exports));
  const app = express2();
  app.set("trust proxy", 1);
  app.use((req, _res, next) => {
    rewriteVercelPath(req);
    next();
  });
  app.use(apiSecurityHeaders);
  app.use(createRateLimiter({ namespace: "vercel-api", windowMs: 6e4, maxRequests: 300 }));
  app.use(jsonBodyParser());
  app.use(jsonParseErrorHandler);
  app.use("/api/tools/audit/start", createRateLimiter({ namespace: "audit-start", windowMs: 6e4, maxRequests: 20 }));
  app.use("/tools/audit/start", createRateLimiter({ namespace: "audit-start-direct", windowMs: 6e4, maxRequests: 20 }));
  app.use("/api/tools", apiRouter2);
  app.use("/tools", apiRouter2);
  app.use((req, res) => {
    res.status(404).json({
      success: false,
      error: `API route not found: ${req.method} ${req.originalUrl || req.url}`
    });
  });
  app.use(apiErrorHandler);
  cachedApp = app;
  return cachedApp;
}
async function handler(req, res) {
  try {
    const app = await getApp();
    return app(req, res);
  } catch (error) {
    console.error("[api/index] function failed", {
      message: error?.message,
      stack: error?.stack,
      url: req?.url,
      method: req?.method
    });
    if (!res.headersSent) {
      return res.status(500).json({
        success: false,
        error: error?.message || "API function failed"
      });
    }
  }
}
export {
  handler as default
};
